export function getCategoriesInstrumenteJson() {
  const categories = [
    'corMixt',
    'corDeFemei',
    'corDeBarbati',
    'corPentruVociEgale',
    'soprana',
    'mezzoSoprana',
    'alto',
    'tenor',
    'bass',
    'bariton',
    'orchSimfonica',
    'orchDeCamera',
    'orchDeCoarde',
    'concertSolo',
    'vocalSimf',
    'opera',
    'duo',
    'trio',
    'cvartet',
    'sextet',
    'septet',
    'octet',
    'pian',
    'vioara',
    'viola',
    'violoncel',
    'contrabas',
    'harpa',
    'chitara',
    'flaut',
    'oboi',
    'clarinet',
    'fagot',
    'corn',
    'trompeta',
    'trombon',
    'tuba',
    'percutie',
  ];

  return categories;
}
