export function getPerformanceListJson() {
  const performanceList = [
    {
      id: 1,
      NumeCompozitor: 'ALBU Sandu',
      n: '22 August 1897',
      Stil: 'Muzică de cameră',
      Titlu: 'Siciliana pentru violoncel și pian',
      AnulComp: 1958,
      Detalii: '',
    },
    {
      id: 2,
      NumeCompozitor: 'ALBIN Anatol',
      n: '5 Iulie 1903',
      Stil: 'Muzică simfonică',
      Titlu: 'Octombrie biruitor',
      AnulComp: 1960,
      Detalii: 'Cantată pentru soliști, cor mixt și orchestră',
    },
    {
      id: 3,
      NumeCompozitor: 'ALBIN Anatol',
      n: '5 Iulie 1903',
      Stil: 'Muzică simfonică',
      Titlu: 'O seară veselă',
      AnulComp: 1938,
      Detalii: 'Potpuriu românesc',
    },
    {
      id: 4,
      NumeCompozitor: 'ALBU Sandu',
      n: '5 Iulie 1903',
      Stil: 'Muzică simfonică',
      Titlu: 'Pe ulița armenească',
      AnulComp: 1935,
      Detalii: 'Parafrază pentru jazz simfonic',
    },
    {
      id: 5,
      NumeCompozitor: 'ALBIN Anatol',
      n: '5 Iulie 1903',
      Stil: 'Muzică simfonică',
      Titlu: 'Tristă duminică',
      AnulComp: 1936,
      Detalii: 'Parafrază pentru jazz simfonic',
    },
    {
      id: 6,
      NumeCompozitor: 'ALEXANDRA Liana',
      n: '27 Mai 1947',
      Stil: 'Muzică simfonică',
      Titlu: 'Simfonia a II-a op 16',
      AnulComp: 1978,
      Detalii: '',
    },
    {
      id: 7,
      NumeCompozitor: 'ALEXANDRA Liana',
      n: '27 Mai 1947',
      Stil: 'Muzică simfonică',
      Titlu: 'Două imagini oentru orchestră op 20',
      AnulComp: 1978,
      Detalii: '',
    },
    {
      id: 8,
      NumeCompozitor: 'ALEXANDRA Liana',
      n: '27 Mai 1947',
      Stil: 'Muzică simfonică',
      Titlu: 'Concert pentru violă, flaut și orchestră de cameră op  23',
      AnulComp: 1982,
      Detalii: '',
    },
    {
      id: 9,
      NumeCompozitor: 'ALEXANDRESCU Romeo',
      n: '17 Iunie 1902',
      Stil: 'Muzică de cameră',
      Titlu: 'Trio pentru 2 viori și pian',
      AnulComp: 1923,
      Detalii: '',
    },
    {
      id: 10,
      NumeCompozitor: 'ALEXANDRESCU Romeo',
      n: '17 Iunie 1902',
      Stil: 'Muzică de cameră',
      Titlu: 'Trio pentru 3 violoncele',
      AnulComp: 1930,
      Detalii: '',
    },
    {
      id: 11,
      NumeCompozitor: 'ANDREESCU Petre',
      n: '14 August 1893',
      Stil: 'Solo corzi',
      Titlu: 'Lala, Lili, Lola, Lulu',
      AnulComp: 1934,
      Detalii: '',
    },
    {
      id: 12,
      NumeCompozitor: 'ANDREESCU Petre',
      n: '14 August 1893',
      Stil: 'Solo corzi',
      Titlu: 'Cântecele mele vântul le-a furat',
      AnulComp: 1935,
      Detalii: '',
    },
    {
      id: 13,
      NumeCompozitor: 'ANDREESCU Petre',
      n: '14 August 1893',
      Stil: 'Solo corzi',
      Titlu: 'Doar tu',
      AnulComp: '',
      Detalii: '',
    },
    {
      id: 14,
      NumeCompozitor: 'ANDREESCU Petre',
      n: '14 August 1893',
      Stil: 'Solo corzi',
      Titlu: 'Amorul e un mix ștrengar',
      AnulComp: '',
      Detalii: '',
    },
    {
      id: 15,
      NumeCompozitor: 'ANDREESCU-SKELETTY Mihail (Andreescu-Iassy, M )',
      n: '19 Iulie 1882',
      Stil: 'Solo Suflatori',
      Titlu: 'Lazăr Cernescu de la Rusca',
      AnulComp: '',
      Detalii: 'Operă',
    },
    {
      id: 16,
      NumeCompozitor: 'ANDREESCU-SKELETTY Mihail (Andreescu-Iassy, M )',
      n: '19 Iulie 1882',
      Stil: 'Solo Suflatori',
      Titlu: 'Siciliana pentru violoncel și pian',
      AnulComp: 1958,
      Detalii: 'Operă',
    },
    {
      id: 17,
      NumeCompozitor: 'ANDRONIC Ștefan',
      n: '22 Decembrie 1921',
      Stil: 'Muzică corală',
      Titlu: 'Pe Sabar și Săbărel',
      AnulComp: 1968,
      Detalii: 'pentru cor mixt',
    },
    {
      id: 18,
      NumeCompozitor: 'ANDRONIC Ștefan',
      n: '22 Decembrie 1921',
      Stil: 'Muzică corală',
      Titlu: 'Cât ești de frumoasă țară',
      AnulComp: 1969,
      Detalii: 'pentru cor mixt',
    },
  ];

  return performanceList;
}
